FROM ruby:latest

RUN useradd -m app && \
	mkdir -p rails && \
	chown app /rails


WORKDIR /rails
COPY rails ./

EXPOSE 3000

RUN apt-get update && apt install -y --allow-unauthenticated nodejs && \
    nodejs -v && \
    gem install bundler && \
    bundle install && \
    rails db:migrate && \
	rm -rf /var/lib/apt/lists/* && \
	chown -R app /rails

USER app


CMD ["rails", "s"]