FROM ubuntu:16.04

RUN useradd -m app

RUN mkdir -p backend
RUN chown app /backend

WORKDIR /backend

COPY backend ./


#RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/path

#COPY backend ./

ENV FRONT_URL=http://localhost:5000


RUN apt-get update && apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    npm install && \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/*

EXPOSE 8000

CMD ["npm", "start"]