FROM ubuntu:16.04

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/path

COPY frontend ./

ENV API_URL=http://localhost:8000
EXPOSE 5000

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    npm install && npm install -g serve && npm install -g webpack webpack-cli #&& \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/*


CMD ["npm", "start"]
